--Leaves Product 1
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Leaves', 1.500, 5.0, 'Costa Rica', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in semper nisl. Vestibulum rutrum sollicitudin velit sit amet bibendum. In vitae vestibulum turpis. Sed imperdiet vehicula augue at semper.', 30, 'LEAVES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Mango Leaves', 1.250, 6.0, 'Nicaragua', 'Donec sodales lectus nec diam laoreet rutrum. Nam molestie, sapien vitae ullamcorper ornare, mauris mi malesuada nisl, quis ultricies risus enim vitae nunc. Donec iaculis pulvinar aliquet.', 30, 'LEAVES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Raspberry Leaves', 1.200, 5.50, 'Costa Rica', 'Curabitur id luctus velit. Aliquam sed sollicitudin risus. Sed in nisl dui. Nulla facilisi. Nullam porttitor quam vehicula, vehicula erat vitae, euismod elit.', 30, 'LEAVES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Blueberries Leaves', 1.350, 6.50, 'Puerto Rico', 'Cras eu tortor ligula. Vivamus sed elit id nisi lobortis sagittis.Fusce imperdiet mauris vel sollicitudin pharetra.', 30, 'LEAVES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Strawberries Leaves', 1.200, 5.0, 'El Salvador', 'Phasellus imperdiet purus in posuere finibus. Vivamus vel massa varius, vestibulum arcu ut, lacinia nisl. Proin efficitur odio et nibh venenatis elementum. Etiam eget elit bibendum velit tristique congue in vitae nunc.', 30, 'LEAVES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Jamaican flower Leaves', 1.350, 7.0, 'Jamaica', 'Cras cursus ligula eget dictum egestas. Nullam scelerisque eget lacus quis suscipit. Curabitur sit amet ex vitae nibh mollis iaculis. Curabitur faucibus aliquam enim et varius.', 30, 'LEAVES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Lemon Leaves', 1.300, 4.80, 'Panama', 'Praesent lacinia nibh laoreet metus facilisis pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc sit amet congue erat, id interdum quam.Vestibulum at lectus non lectus imperdiet sollicitudin id quis lacus. Sed sagittis nisi vel dictum bibendum.', 30, 'LEAVES');

--Fruit Product 2
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Bananas', 0.500, 2.50, 'Costa Rica, Colombia, Panama', 'Vestibulum ac nisi a lectus gravida facilisis. Nullam quis sem ipsum. Donec imperdiet magna eu elit scelerisque ullamcorper. Mauris at risus ipsum.', 20, 'FRUIT');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Apples', 0.350, 2.50, 'Spain', 'In rutrum mauris eu nisi tincidunt, et venenatis nisl accumsan. Maecenas luctus rutrum interdum. Mauris nunc ligula, interdum et nibh at, semper auctor ante.', 20, 'FRUIT');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Mango', 0.500, 4.50, 'Florida', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum elit eros, lacinia a nunc a, consequat pretium mi.', 20, 'FRUIT');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Strawberries', 0.500, 3.80, 'Spain', 'Ut dapibus tellus in risus malesuada imperdiet. Aenean a placerat tortor, sed vestibulum urna.', 20, 'FRUIT');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Passion Fruit', 0.500, 3.80, 'Costa Rica, Colombia', 'Proin nec leo nec nulla maximus fermentum. Proin porta mattis ante, sed lacinia risus ullamcorper id.', 20, 'FRUIT');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Oranges', 1.000, 4.20, 'Italy', 'Pellentesque ac condimentum nisi. Nam sem ante, consequat vitae porta ut, varius sit amet tortor.', 20, 'FRUIT');

--Vegs Product 3
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Broccoli', 0.500, 2.20, 'Spain', 'Pellentesque nibh elit, rutrum at dui ut, ullamcorper blandit ligula. Mauris cursus dolor quis diam scelerisque convallis.', 20, 'VEGETABLES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Brussels Sprouts', 1.100, 4.00, 'UK', 'Suspendisse pretium lorem vel interdum porta. Integer dictum felis sit amet lobortis sollicitudin. Cras in egestas magna, nec bibendum ex.', 20, 'VEGETABLES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic French Beans', 0.300, 3.00, 'Portugal', 'Donec placerat sed augue ut pulvinar. In dictum molestie ex a fermentum. Praesent dapibus dui a justo mattis, vitae feugiat eros hendrerit.', 20, 'VEGETABLES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Mushrooms', 0.250, 2.20, 'Spain', 'Morbi bibendum nisi erat, vitae egestas magna ornare in. Aenean lectus neque, dignissim quis massa ac, dapibus convallis felis. Integer placerat tincidunt faucibus. In ullamcorper eleifend auctor.', 20, 'VEGETABLES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Tomatoes', 0.500, 2.90, 'Italy', 'Vivamus cursus tincidunt iaculis. In posuere, diam vel sodales blandit, urna tortor tristique risus, quis posuere ipsum augue nec sapien.', 20, 'VEGETABLES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Eggs', 0.500, 2.20, 'Spain', 'Vestibulum scelerisque eu tellus sed rhoncus. In non tortor et mi efficitur tincidunt id sodales tortor. Phasellus fringilla pretium bibendum.', 20, 'VEGETABLES');
INSERT INTO PRODUCTS (PRODUCTID, TITLEPRODUCT, WEIGHT, PRICE, COUNTRYOFORIGIN, DESCRIPTION, QUANTITY, TYPEOFPRODUCT) values (PRODUCTS_SEQ.nextval, 'Organic Spinach', 0.250, 2.70, 'Spain', 'Curabitur quis vulputate purus. Curabitur dictum tempus leo, vel viverra metus sodales in.', 20, 'VEGETABLES');

--Users
INSERT INTO USERS(ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES (USER_SEQ.nextval, 'Admin', 'password01', 'Lore', 'Lolo');
INSERT INTO USERS(ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES (USER_SEQ.nextval, 'Juli', 'pwd1', 'Juli', 'jeje');
